import type { Metadata } from 'next'
import './globals.css'
import { AppProvider } from '@/contexts/providers'
import Image from 'next/image'
import imgone from '../assets/footer-image.png'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css';

export const metadata: Metadata = {
  title: 'Homepage',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <AppProvider>
        <body className='h-screen bgcolor'>
          <main className='h-full'>
            <div className='h-full flex flex-col justify-between bgcolor'>
              {children}
              <div className=''>
                <div className="bg-image-footer">
                  <Image src={imgone} alt="imgone" width={1440} height={100} />
                </div>
              </div>
            </div>
          </main>
          <ToastContainer />
        </body>
      </AppProvider>
    </html>
  )
}
