import React from 'react';
import AddNewMovieForm from '../components/addNewMovie';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Add New Movie',
  description: 'Generated by create next app',
}

const AddNewMovie: React.FC = () => {
  return (
    <>
     <AddNewMovieForm />
    </>
  )
}

export default AddNewMovie;